/// Represents a geographic region hypothesis generated by the inference engine.
/// These are probabilistic regions inferred from memory clues.
class RegionHypothesis {
  /// Unique identifier for this hypothesis
  final String id;

  /// The geographic region name (e.g., "Selangor", "Kuala Lumpur", "Penang")
  final String regionName;

  /// Geographic code or identifier
  final String regionCode;

  /// Confidence score for this hypothesis (0.0 - 1.0)
  /// Based on the clues that led to this inference
  final double confidence;

  /// Contributing factors and their individual scores
  /// Maps factor name (e.g., "language_match", "poi_proximity") to score
  final Map<String, double> contributingFactors;

  /// List of clue IDs that supported this hypothesis
  final List<String> supportingClueIds;

  /// Geographic bounds if applicable
  final double? centerLatitude;
  final double? centerLongitude;
  final double? radiusKm;

  /// Reasoning explanation
  final String explanation;

  /// Timestamp of hypothesis generation
  final DateTime generatedAt;

  RegionHypothesis({
    required this.id,
    required this.regionName,
    required this.regionCode,
    required this.confidence,
    required this.contributingFactors,
    required this.supportingClueIds,
    required this.explanation,
    required this.generatedAt,
    this.centerLatitude,
    this.centerLongitude,
    this.radiusKm,
  });

  RegionHypothesis copyWith({
    String? id,
    String? regionName,
    String? regionCode,
    double? confidence,
    Map<String, double>? contributingFactors,
    List<String>? supportingClueIds,
    double? centerLatitude,
    double? centerLongitude,
    double? radiusKm,
    String? explanation,
    DateTime? generatedAt,
  }) {
    return RegionHypothesis(
      id: id ?? this.id,
      regionName: regionName ?? this.regionName,
      regionCode: regionCode ?? this.regionCode,
      confidence: confidence ?? this.confidence,
      contributingFactors: contributingFactors ?? this.contributingFactors,
      supportingClueIds: supportingClueIds ?? this.supportingClueIds,
      centerLatitude: centerLatitude ?? this.centerLatitude,
      centerLongitude: centerLongitude ?? this.centerLongitude,
      radiusKm: radiusKm ?? this.radiusKm,
      explanation: explanation ?? this.explanation,
      generatedAt: generatedAt ?? this.generatedAt,
    );
  }

  @override
  String toString() =>
      'RegionHypothesis(region: $regionName, confidence: ${(confidence * 100).toStringAsFixed(1)}%)';
}
